goat = 'Hey guys, I’m new to overwatch. Is there a reason that they aren’t using any damage heroes? How are they supposed to get kills without dps? Are they deleted or banned or something?'

innit = "Do british people actually exist? I mean, they must be a meme, there is a not a single thing about them. And I mean it. Let's go through the evidence: Where are they from? Not a single country in the world is named Britain. Some people say they come from England, and England is inside Britain, but if that was the case they would be British they would be Englanders. Also, heard some silly theories about them coming from whales. Guys, no, whale people do not exist. Whales live in the sea. There is a consensus on british people coming from Europe, but then we are left with a whole continent of possible locations. That's as good as nothing. What do they eat? Every country has at least one main dish. Even the US has their burgers. But these british people, what do they eat? Heard some people associating them with tea, but everyone knows that's an Asian thing. Shouldn't they come from Europe? One of these two points must be wrong them. To me, it looks too sketchy. What language do they speak? I challenge you, putting all my money and my ass on the line here, to find a supposed british person speaking their native language. Most of then just speak a broken ENGLISH. Yes, english. Really suspicious, huh? And I even tried to look deeper into it. Maybe british just SOUND like english, just like spanish could sound like portuguese for a non-speaker. So I looked up british dictionary on google and what I found was shocking: every word in there was AMERICAN. I kid you not. What this could mean is beyond my capabilities, but I can safely assure you that british people do not exist."

based = "Based? Based on what? In your dick? Please shut the fuck up and use words properly you fuckin troglodyte, do you think God gave us a freedom of speech just to spew random words that have no meaning that doesn't even correllate to the topic of the conversation? Like please you always complain about why no one talks to you or no one expresses their opinions on you because you're always spewing random shit like poggers based cringe and when you try to explain what it is and you just say that it's funny like what? What the fuck is funny about that do you think you'll just become a stand-up comedian that will get a standing ovation just because you said cum in the stage? HELL NO YOU FUCKIN IDIOT, so please shut the fuck up and use words properly"

simp = "What the fuck man. I'm literally sitting here on the verge of tears. Slaving away in this dead end job saving up for the end of the month splash. I was this close. Maybe I should have done that overtime, if I could get her that money earlier I might have been able to convince her in the dono message. She needs a man that can treat her right, a man like me. I would open the car door for her EVERY TIME, I would pull out her chair at a restaurant, I would lay my twitch hoodie over puddles to protect her from the filth."

pee = "Pee is currently dripping down my leg, it is warm. :)"

furry = "I'm not a furry, I swear! I just really, really like anthropomorphic animals and the artistic potential you can get out of them. I mean, sure I drew what is essentially an anthropomorphic bunny as a new OC as of recent, but doesn't mean I'm a furry! Sure, I love looking at other people's art and it may steadily be becoming a part of my visual aesthetic, but I'll tell you yet again: I AM NOT A FURRY. I never will be, I would feel great shame if I were a furry."
